org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:TieredStopAtLevel=1 -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.jvm.target=17
org.gradle.parallel=false
org.gradle.workers.max=2
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
android.enableJetifier=false
android.nonTransitiveRClass=true
org.gradle.vfs.watch=false
kotlin.incremental=false
