org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC -Dfile.encoding=UTF-8 -XX:TieredStopAtLevel=1 -Dkotlin.daemon.jvm.options="-Xmx2g"
android.useAndroidX=true
kotlin.jvm.target=17
org.gradle.parallel=true
org.gradle.workers.max=4
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
android.enableJetifier=false
android.nonTransitiveRClass=true
org.gradle.vfs.watch=false
kotlin.incremental=false
