org.gradle.jvmargs=-Xmx4g -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError -XX:+UseG1GC -Dfile.encoding=UTF-8 -XX:TieredStopAtLevel=1 -Dkotlin.compiler.execution.strategy="in-process"
android.useAndroidX=true
org.gradle.java.home=C:/Program Files/Android/Android Studio1/jbr
kotlin.jvm.target=17
org.gradle.parallel=true
org.gradle.workers.max=4
org.gradle.caching=true
org.gradle.configureondemand=true
org.gradle.daemon=true
android.enableJetifier=true
android.nonTransitiveRClass=true
org.gradle.vfs.watch=true
